### PR TITLE
Fix #200 where swagger used the wrong IP to retrieve well-known info

### LINKED ISSUE #200: Docker Dev: Swagger authorization issuer URL doesn't work
**Describe the bug**
The authorization URL in Swagger is set to `https://172.16.238.3/connect/authorize`, which does not respond on my computer.

**To Reproduce**
1. Clone the backend repo
2. Execute `docker-compose up`
3. Visit Swagger
4. Click 'Authorize'
image
5. Get redirected to `https://172.16.238.3/connect/authorize?response_type=token&client_id=Swagger-UI&redirect_uri=https%3A%2F%2Flocalhost%3A5001%2Foauth2-redirect.html&scope=dex-api&state=....` with no response.

**Expected behavior**
To become authorized in Swagger

**Screenshots**
See above.

**Additional context**
The following appears in the Docker logs:
```api_1       | [17:19:53 Error] Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler
api_1       | Exception occurred while processing message.
api_1       | System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://172.16.238.3/.well-known/openid-configuration'.
api_1       |  ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://172.16.238.3/.well-known/openid-configuration'.
api_1       |  ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
api_1       |  ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
api_1       |    at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
api_1       |    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
api_1       | --- End of stack trace from previous location where exception was thrown ---
api_1       |    at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
api_1       |    at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
api_1       |    at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
api_1       |    at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
api_1       |    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
api_1       | --- End of stack trace from previous location where exception was thrown ---
api_1       |    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
api_1       |    --- End of inner exception stack trace ---
api_1       |    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
api_1       |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
api_1       |    --- End of inner exception stack trace ---
api_1       |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
api_1       |    at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
api_1       |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
api_1       |    --- End of inner exception stack trace ---
api_1       |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
api_1       |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
api_1       | 
api_1       | [17:19:53 Error] IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler
api_1       | IDX20803: Unable to obtain configuration from: 'https://172.16.238.3/.well-known/openid-configuration'.
api_1       | System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://172.16.238.3/.well-known/openid-configuration'.
api_1       |  ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://172.16.238.3/.well-known/openid-configuration'.
api_1       |  ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
api_1       |  ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
api_1       |    at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
api_1       |    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
api_1       |    at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
api_1       | --- End of stack trace from previous location where exception was thrown ---
api_1       |    at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
api_1       |    at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
api_1       |    at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
api_1       |    at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
api_1       |    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
api_1       | --- End of stack trace from previous location where exception was thrown ---
api_1       |    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
api_1       |    --- End of inner exception stack trace ---
api_1       |    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
api_1       |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
api_1       |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
api_1       |    --- End of inner exception stack trace ---
api_1       |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
api_1       |    at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
api_1       |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
api_1       |    --- End of inner exception stack trace ---
api_1       |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
api_1       |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
api_1       |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
api_1       |    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
api_1       |    at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
api_1       |    at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()
api_1       | 
api_1       | [17:19:53 Information] IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler
api_1       | Bearer was not authenticated. Failure message: IDX20803: Unable to obtain configuration from: 'https://172.16.238.3/.well-known/openid-configuration'.
api_1       | 
```

### PR DESCRIPTION
**Pull request by Brend-Smits**
## Description

Swagger auth was using the internal docker IP. This won't work as you need to reference localhost:5005. 
Identity and API also weren't running on 5001/5000 and 5004/5005 as aspnetcore_urls were not referencing the ports correctly. 
In addition to that, I removed the part where direct ip's were referenced instead of service names. This change makes things easier to follow and less likely to break in the future, let Docker do it's DNS magic to resolve the IP address from the container.

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I did not update API Controllers, if I did, I added/changed Postman tests
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Run the backend with docker-compose up --build
2. Use the green lock in swagger to authorize yourself
3. Try the user-get endpoint and see if everything works fine.

## Link to issue

Closes: #200

### CODE REVIEW

File: API/Startup.cs [hunk 1]
```diff
@@ -151,20 +151,22 @@ public void ConfigureServices(IServiceCollection services)
                         }
                     });
                 o.IncludeXmlComments($"{AppDomain.CurrentDomain.BaseDirectory}{typeof(Startup).Namespace}.xml", true);
+                Uri authorizationUrl = Environment.IsDevelopment() ? new Uri(Config.IdentityServer.DevelopmentIdentityUrl + "/connect/authorize") : new Uri(Config.IdentityServer.IdentityUrl + "/connect/authorize");
```
Comment (matir8) [inline API/Startup.cs:154]: Not a fan of this rule, but we ban the use of the ternary operator in our [style guide](https://github.com/DigitalExcellence/dex-backend/wiki/Coding-guidelines#banned-operators). Maybe we could add a private helper method to build the `authorizationUrl`?

**Review by matir8 — CHANGES_REQUESTED** [review]
Thanks for fixing this bug! I have just one tiny little code-style comment. Other than that it looks good.

File: API/Startup.cs (hunk 1 above)
Comment (Brend-Smits) [reply API/Startup.cs:154]: You're right, thanks!

**Review by r4gn4r0k1 — APPROVED** [review]

**Review by RensvdLinden — APPROVED** [review]

**Review by matir8 — APPROVED** [review]
